// Auto-generated by `ai-memory install-hooks --agent opencode --apply`.
// Edit by re-running the command, not by hand — install-hooks
// will overwrite this file (with a `.bak-<ts>` backup) on each
// re-run.

import type { Plugin } from "@opencode-ai/plugin";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { homedir } from "node:os";

const SERVER = "http://127.0.0.1:49374".replace(/\/+$/, "");
const AGENT = "opencode";
const TOKEN: string | null = null;


function timeoutSignal(ms: number): AbortSignal | undefined {
  if (typeof AbortSignal === "undefined") return undefined;
  const factory = (AbortSignal as unknown as { timeout?: (ms: number) => AbortSignal }).timeout;
  return factory ? factory(ms) : undefined;
}

function authHeaders(): Record<string, string> {
  return TOKEN ? { Authorization: `Bearer ${TOKEN}` } : {};
}

const HOOK_QUEUE_MAX = 100;
const HOOK_FLUSH_INTERVAL_MS = 2000;
const HOOK_FLUSH_THRESHOLD = 20;
const HOOK_INTER_REQUEST_DELAY_MS = 50;
const HOOK_REQUEST_TIMEOUT_MS = 2000;
const HOOK_DISPOSE_DRAIN_BUDGET_MS = 2000;
const HOOK_IMMEDIATE_EVENTS = new Set(["session-start", "stop", "session-end", "pre-compact"]);

type HookQueueItem = { event: string; url: URL; payload: Record<string, unknown> };
const hookQueue: HookQueueItem[] = [];
let hookFlushTimer: ReturnType<typeof setTimeout> | undefined;
let hookDraining = false;
let hookDrainPromise: Promise<void> | undefined;

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function scheduleHookFlush(): void {
  if (hookFlushTimer) return;
  hookFlushTimer = setTimeout(() => {
    hookFlushTimer = undefined;
    void requestHookDrain();
  }, HOOK_FLUSH_INTERVAL_MS);
  hookFlushTimer.unref?.();
}

function requestHookDrain(): Promise<void> {
  if (!hookDrainPromise) {
    hookDrainPromise = drainHookQueue().finally(() => {
      hookDrainPromise = undefined;
      if (hookQueue.length > 0) void requestHookDrain();
    });
  }
  return hookDrainPromise;
}

function disposeDrainTimeout(): Promise<void> {
  return new Promise((resolve) => {
    const timer = setTimeout(resolve, HOOK_DISPOSE_DRAIN_BUDGET_MS);
    timer.unref?.();
  });
}

async function drainHookQueueForDispose(): Promise<void> {
  await Promise.race([requestHookDrain(), disposeDrainTimeout()]);
}

function enqueueHook(event: string, url: URL, payload: Record<string, unknown>): void {
  if (hookQueue.length >= HOOK_QUEUE_MAX) hookQueue.shift();
  hookQueue.push({ event, url, payload });
  if (HOOK_IMMEDIATE_EVENTS.has(event) || hookQueue.length >= HOOK_FLUSH_THRESHOLD) {
    void requestHookDrain();
  } else {
    scheduleHookFlush();
  }
}

async function drainHookQueue(): Promise<void> {
  if (hookDraining) return;
  hookDraining = true;
  if (hookFlushTimer) {
    clearTimeout(hookFlushTimer);
    hookFlushTimer = undefined;
  }
  try {
    while (hookQueue.length > 0) {
      const item = hookQueue.shift();
      if (!item) break;
      try {
        await fetch(item.url, {
          method: "POST",
          headers: { "Content-Type": "application/json", ...authHeaders() },
          body: JSON.stringify(item.payload),
          signal: timeoutSignal(HOOK_REQUEST_TIMEOUT_MS),
        }).catch(() => undefined);
      } catch (_e) {
        // Best-effort capture. Hooks must never block the agent.
      }
      if (hookQueue.length > 0) await sleep(HOOK_INTER_REQUEST_DELAY_MS);
    }
  } finally {
    hookDraining = false;
  }
}

function findMarker(cwd: string | undefined): string | undefined {
  if (!cwd) return undefined;
  let dir = resolve(cwd);
  const home = homedir();
  while (dir && dir !== dirname(dir)) {
    const marker = join(dir, ".ai-memory.toml");
    if (existsSync(marker)) return marker;
    if (home && dir === home) return undefined;
    dir = dirname(dir);
  }
  return undefined;
}

function tomlKey(text: string, key: string): string | undefined {
  const re = new RegExp(`^\\s*${key}\\s*=\\s*"([^"]*)"`);
  for (const line of text.split(/\r?\n/)) {
    const match = re.exec(line);
    if (match) return match[1];
  }
  return undefined;
}


function repoRootProject(cwd: string | undefined): string | undefined {
  if (!cwd) return undefined;
  try {
    const inside = execFileSync("git", ["-C", cwd, "rev-parse", "--is-inside-work-tree"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (inside !== "true") return undefined;
    const common = execFileSync("git", ["-C", cwd, "rev-parse", "--path-format=absolute", "--git-common-dir"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (!common) return undefined;
    const root = dirname(common);
    if (!root || root === dirname(root)) return undefined;
    return basename(root);
  } catch (_e) {
    return undefined;
  }
}
function applyMarkerParams(url: URL, cwd: string | undefined): void {
  const marker = findMarker(cwd);
  if (!marker || !cwd) return;
  url.searchParams.set("cwd", cwd);
  try {
    const body = readFileSync(marker, "utf8");
    const workspace = tomlKey(body, "workspace");
    const project = tomlKey(body, "project");
    const projectStrategy = tomlKey(body, "project_strategy");
    const dropSubagent = tomlKey(body, "drop_subagent_captures");
    if (workspace) url.searchParams.set("workspace", workspace);
    if (project) url.searchParams.set("project", project);
    if (projectStrategy) url.searchParams.set("project_strategy", projectStrategy);
    if (dropSubagent) url.searchParams.set("drop_subagent", dropSubagent);
    if (!project && (projectStrategy === "repo-root" || projectStrategy === "repo_root")) {
      const repoProject = repoRootProject(cwd);
      if (repoProject) url.searchParams.set("project", repoProject);
    }
  } catch (_e) {
  }
}

function sessionID(input: unknown): string | undefined {
  const value = input as any;
  return value?.sessionID ?? value?.sessionId ?? value?.session_id ?? value?.info?.id;
}

function textFromParts(parts: unknown): string {
  if (!Array.isArray(parts)) return "";
  return parts
    .map((part: any) => {
      if (part?.type === "text" && typeof part.text === "string") return part.text;
      if (part?.type === "subtask" && typeof part.prompt === "string") return part.prompt;
      if (part?.type === "file" && typeof part.filename === "string") return `[file: ${part.filename}]`;
      return "";
    })
    .filter(Boolean)
    .join("\n\n")
    .trim();
}

const sessionCwds = new Map<string, string>();
const startedSessions = new Set<string>();
const handoffChecked = new Set<string>();
const preCompactLast = new Map<string, number>();

function cwdFor(id: string | undefined, directory: string): string {
  return (id && sessionCwds.get(id)) || directory;
}

function rememberCwd(id: string | undefined, cwd: string | undefined): void {
  if (id && cwd) sessionCwds.set(id, cwd);
}

function startSession(id: string | undefined, cwd: string, extra: Record<string, unknown> = {}): void {
  if (!id || startedSessions.has(id)) return;
  startedSessions.add(id);
  rememberCwd(id, cwd);
  postHook("session-start", { sessionID: id, cwd, ...extra });
}

function endSession(id: string | undefined, directory: string, cwd?: string): void {
  if (!id || !startedSessions.delete(id)) return;
  const resolvedCwd = cwd || cwdFor(id, directory);
  postHook("session-end", { sessionID: id, cwd: resolvedCwd });
  sessionCwds.delete(id);
  handoffChecked.delete(id);
  preCompactLast.delete(id);
}

function postPreCompact(id: string | undefined, directory: string): void {
  startSession(id, cwdFor(id, directory));
  const key = id || "unknown";
  const now = Date.now();
  const last = preCompactLast.get(key) ?? 0;
  if (now - last < 1000) return;
  preCompactLast.set(key, now);
  postHook("pre-compact", { sessionID: id, cwd: cwdFor(id, directory) });
}

function postHook(event: string, payload: Record<string, unknown>): void {
  const url = new URL(`${SERVER}/hook`);
  url.searchParams.set("event", event);
  url.searchParams.set("agent", AGENT);
  applyMarkerParams(url, typeof payload.cwd === "string" ? payload.cwd : undefined);
  try {
    enqueueHook(event, url, payload);
  } catch (_e) {
    // Best-effort capture. Hooks must never block the agent.
  }
}

async function fetchHandoff(cwd: string): Promise<string | undefined> {
  const url = new URL(`${SERVER}/handoff`);
  url.searchParams.set("agent", AGENT);
  url.searchParams.set("cwd", cwd);
  applyMarkerParams(url, cwd);
  try {
    const response = await fetch(url, {
      headers: authHeaders(),
      signal: timeoutSignal(1000),
    });
    const text = (await response.text()).trim();
    return text.length > 0 ? text : undefined;
  } catch (_e) {
    return undefined;
  }
}

export const AiMemoryHooks: Plugin = async ({ directory }) => {
  return {
    dispose: async () => {
      for (const id of Array.from(startedSessions)) {
        endSession(id, directory);
      }
      await drainHookQueueForDispose();
    },
    event: async (input) => {
      const event = (input as any).event;
      const properties = event?.properties ?? {};
      if (event?.type === "session.created") {
        const info = properties.info ?? {};
        const id = properties.sessionID ?? info.id;
        const cwd = info.directory ?? directory;
        startSession(id, cwd, {
          title: info.title,
          projectID: info.projectID,
        });
      }
      if (event?.type === "session.idle") {
        const id = properties.sessionID;
        startSession(id, cwdFor(id, directory));
        postHook("stop", { sessionID: id, cwd: cwdFor(id, directory) });
      }
      if (event?.type === "session.deleted") {
        const info = properties.info ?? {};
        const id = properties.sessionID ?? info.id;
        endSession(id, directory, info.directory);
      }
      if (event?.type === "session.compacted") {
        const id = properties.sessionID;
        postPreCompact(id, directory);
      }
    },
    "chat.message": async (input, output) => {
      const id = sessionID(input);
      const cwd = cwdFor(id, directory);
      startSession(id, cwd, { agent: (input as any).agent, model: (input as any).model });
      postHook("user-prompt", {
        sessionID: id,
        cwd,
        agent: (input as any).agent,
        model: (input as any).model,
        messageID: (input as any).messageID,
        prompt: textFromParts((output as any).parts),
      });
    },
    "tool.execute.before": async (input, output) => {
      const id = sessionID(input);
      startSession(id, cwdFor(id, directory));
      postHook("pre-tool-use", {
        sessionID: id,
        cwd: cwdFor(id, directory),
        tool: (input as any).tool,
        callID: (input as any).callID,
        args: (output as any).args,
      });
    },
    "tool.execute.after": async (input, output) => {
      const id = sessionID(input);
      startSession(id, cwdFor(id, directory));
      postHook("post-tool-use", {
        sessionID: id,
        cwd: cwdFor(id, directory),
        tool: (input as any).tool,
        callID: (input as any).callID,
        args: (input as any).args,
        title: (output as any).title,
        output: (output as any).output,
        metadata: (output as any).metadata,
      });
    },
    "experimental.session.compacting": async (input) => {
      const id = sessionID(input);
      postPreCompact(id, directory);
    },
    "experimental.chat.system.transform": async (input, output) => {
      const id = sessionID(input);
      if (!id || handoffChecked.has(id)) return;
      handoffChecked.add(id);
      startSession(id, cwdFor(id, directory));
      const handoff = await fetchHandoff(cwdFor(id, directory));
      if (handoff) (output as any).system.push(handoff);
    },
  };
};

export default AiMemoryHooks;
